export const carsData = [
  {
    id: 1,
    brand: "Tesla",
    model: "Model 3",
    price: 45000,
    year: 2019,
    fuelType: "Eléctrico",
    image: "/tesla-model-3.jpg",
    description:
      "Sedán eléctrico de alto rendimiento con tecnología autopilot avanzada",
  },
  {
    id: 2,
    brand: "BMW",
    model: "X5",
    price: 72000,
    year: 2018,
    fuelType: "Gasolina",
    image: "/bmw-x5.jpg",
    description:
      "SUV de lujo con interior premium y sistema de conducción avanzado",
  },
  {
    id: 3,
    brand: "Toyota",
    model: "Corolla",
    price: 28000,
    year: 2024,
    fuelType: "Gasolina",
    image: "/toyota-corolla.jpg",
    description: "Sedán compacto confiable y eficiente en combustible",
  },
  {
    id: 4,
    brand: "Audi",
    model: "A4",
    price: 55000,
    year: 2016,
    fuelType: "Gasolina",
    image: "/audi-a4.jpg",
    description:
      "Sedán ejecutivo con diseño elegante y tecnología de vanguardia",
  },
  {
    id: 5,
    brand: "Honda",
    model: "Civic",
    price: 32000,
    year: 2022,
    fuelType: "Gasolina",
    image: "/honda-civic.jpg",
    description: "Sedán deportivo con excelente maniobrabilidad",
  },
  {
    id: 6,
    brand: "Mercedes",
    model: "C-Class",
    price: 65000,
    year: 2021,
    fuelType: "Gasolina",
    image: "/mercedes-c-class.jpg",
    description: "Sedán de lujo alemán con máxima comodidad y seguridad",
  },
  {
    id: 7,
    brand: "Tesla",
    model: "Model Y",
    price: 58000,
    year: 2020,
    fuelType: "Eléctrico",
    image: "/tesla-model-y.jpg",
    description: "SUV eléctrico versátil con gran autonomía",
  },
  {
    id: 8,
    brand: "Volkswagen",
    model: "Golf",
    price: 35000,
    year: 2019,
    fuelType: "Gasolina",
    image: "/volkswagen-golf.jpg",
    description: "Hatchback compacto versátil para la ciudad",
  },
];
